#!/usr/bin/env python
'''
Chute is a simple discrete event simulator for Python.

Usage: chute [-h] -n NUM -t TIME [-f FMT] MODEL [MODEL ...]

Options:
  -h --help        show this help message and exit
  -n --num NUM     number of simulations to run
  -t --time TIME   simulation time to run each iteration for
  -f --format FMT  csv (default) or json output format
'''
from chute import Simulator
from docopt import docopt
import os
import sys


if __name__ == '__main__':
    args = docopt(__doc__)

    # Verify that our args are OK.
    try:
        args['--num'] = int(args['--num'])
        assert args['--num'] > 0
    except:
        print 'num must be > 0'
        sys.exit(1)

    try:
        args['--time'] = float(args['--time'])
        assert args['--time'] > 0
    except:
        print 'time must be > 0'
        sys.exit(1)

    if args['--format'] != 'json':
        args['--format'] = 'csv'

    for num in range(args['--num']):
        # Load the model file.s This will register all our processes
        # with chute. We reload the environment before each simulation.
        for model in args['MODEL']:
            exec(os.linesep.join(open(model)))

        # And run the simulator
        s = Simulator(num=num, out=sys.stdout, fmt=args['--format'])
        s.run(args['--time'])
