#!/usr/bin/env python

from argparse import ArgumentParser
from chute import Simulator
import os
import sys

if __name__ == '__main__':
    # Set up command line     .
    parser = ArgumentParser(description='Run the chute simulator.')

    parser.add_argument(
        'models', nargs='+', metavar='MODEL',
        help='model file to incorporate in the simulation'
    )
    parser.add_argument(
        '-t', '--time', dest='time', type=int, metavar='TIME', required=True,
        help='clock time to run simulation for'
    )
    parser.add_argument(
        '-f', '--format', dest='format', metavar='FMT',
        help='csv (default) or json'
    )

    # Get and check command line args.
    args = parser.parse_args()
    if not args.models:
        parser.error('model file required')

    if args.time <= 0:
        parser.error('time must be > 0')

    if args.format:
        if args.format not in ('csv', 'json'):
            parser.error('valid output formats are csv and json')
    else:
        args.format = 'csv'

    # Load the model file. This will register all our processes with chute.
    for model in args.models:
        exec(os.linesep.join(open(model)))

    # And run the simulator
    s = Simulator(out=sys.stdout, fmt=args.format)
    s.run(args.time)
